### ISSUE TITLE
Boucle infinie

### ISSUE THREAD

**Issue by felixsoum** [Yvilior/ProjetNarratif#1]
Je pense qu'il y a une boucle infinie dans le jeu. Je ne me souviens pas exactement des étapes, mais je pense que j'étais dans les moniteurs. J'ai activé une caméra, et ensuite je me suis endormie pour la quatrième fois. Ensuite les deux messages suivants apparaissaient en boucle infinie:

> Tu t'es endormis pour la quatrieme fois et es actuellement en train de rever:
> (Tapez 'enter' pour continuer)

ensuite

> MiniJeu en court, tapez [x]
> Reponse:

et ca se répète,

**Comment by Yvilior** [comment]
J'ai oublier de faire quitter la salle minijeu4 apres avoir taper 'x' mais c'est bon maintenant
