### ISSUE TITLE
Balancer le temps à attendre

### ISSUE THREAD

**Issue by felixsoum** [Yvilior/ProjetNarratif#2]
J'ai l'impression qu'il faut attendre assez longtemps avant que l'action débute. Ce qui peut désorienter un nouveau joueur qui se demanderait peut-être s'il joue correctement au jeu ou non.

**Comment by Yvilior** [comment]
J'ai préciser que la première heure est pour apprendre les touches et qu'il est possible de skip la première heure une fois habitué.
